### ISSUE TITLE
No package matching 'postgresql-14-sslutils' is available

### ISSUE THREAD

**Issue by marangiop** [EnterpriseDB/edb-ansible#412]
Helllo! I am trying to use the primary-only playbook on localhost and i get the following error:

TASK [edb_devops.edb_postgres.install_dbserver : Install sslutils] *****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'postgresql-14-sslutils' is available"}

This is the command I use for executing the playbook

`
ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false"`

Any idea of what this error is due to and how to solve it?

**Comment by hannahms** [comment]
Hi,

I am trying to replicate this issue and seem to be missing some information. Can you please provide the contents of the `inventory.yml` and `playbook.yml` file you are using in the command as well as the operating system/version you are deploying onto/with? 

Thanks!

**Comment by marangiop** [comment]
Hi @hannahms, thank you for the help!

So If I try to run the following command

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG pg_ssl=false"`

I have the same error as before. 

If I run 

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG pg_ssl=false"`

I get this error 

```
TASK [edb_devops.edb_postgres.setup_repo : Validate Credentials] *********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "repo_username =  or repo_password =  or repo_token =  are not valid!."}
```

I also created an account inside EDP website, but I am not sure where to find the credentials for EDB Repos 1.0 anywhere?

![image](https://user-images.githubusercontent.com/29339953/195653585-7bb7b430-856d-4afb-9e59-2b85af431f6e.png)

Does it mean that i need to have a subscription?

**Comment by hannahms** [comment]
Hi @marangiop,
I apologize, it seems to be that EDB Repo 2.0 is the only one offered to new accounts, so what you are viewing is correct. You can access a 60-day trial token by clicking the Request Trial Access button. Place this token in the command line with the variable `repo_token`.

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG repo_token=<some_token>"`

If you do not want to use the repo, the following command will allow for you to move past this error. `pg_ssl=false` needs to be defined as well as `enable_edb_repo=false` to skip the task. 

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false pg_ssl=false"`

**Comment by marangiop** [comment]
I managed to get my token from EDB. 

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG repo_token=<some_token>"`

Throws this error

TASK [edb_devops.edb_postgres.manage_dbserver : Manage postgres extensions] ********************************************************
failed: [localhost] (item={'name': 'sslutils', 'database': 'postgres', 'state': 'present'}) => {"ansible_loop_var": "line_item", "changed": false, "line_item": {"database": "postgres", "name": "sslutils", "state": "present"}, "msg": "Extension sslutils is not available"}

`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false pg_ssl=false"`

throws this error

TASK [edb_devops.edb_postgres.install_dbserver : Install sslutils] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'postgresql-14-sslutils' is available"}

**Comment by marangiop** [comment]
I am on Ubuntu 20.04 Focal (64 Bit) by the way

**Comment by hannahms** [comment]
Hi there, 

I apologize for the delay in response. 

In regards to the first error, using `ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG repo_token=<some_token>"`, I am not able to replicate this error. Please check both the `/vars/PG_Debian.yml` for roles `init_dbserver` and `manage_dbserver`, and `/vars/edb-ssl.yml` for the `init_dbserver` role. We have more information for variable definitions under each role, for example, [https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/manage_dbserver](https://github.com/EnterpriseDB/edb-ansible/tree/master/roles/manage_dbserver). 

In regards to the second error, I realize there is an error in the code line. The `pg_ssl=false` needs to be changed in the default variable definitions:
- `edb-ansible/roles/init_dbserver/defaults/main.yml` - line 5
- `edb-ansible/roles/install_dbserver/defaults/main.yml` - line 17
This should allow for the following code block to be used while skipping the `Install sslutils` task.  
`ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false"`

**Comment by marangiop** [comment]
Hi @hannahms, I went for the second option you suggested, so I modified 
`edb-ansible/roles/init_dbserver/defaults/main.yml` and `edb-ansible/roles/install_dbserver/defaults/main.yml` as you suggested.

Then ran the command `ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false"`

Here is the output:

```
PLAY [Postgres deployment playbook] ********************************************

TASK [Gathering Facts] *********************************************************
ok: [pemserver1]
ok: [primary1]
ok: [barman1]
ok: [standby2]
ok: [standby1]
ok: [hammerdb1]

TASK [Initialize the user defined variables] ***********************************
ok: [pemserver1]
ok: [barman1]
ok: [primary1]
ok: [standby1]
ok: [standby2]
ok: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_repo : Include the setup_repo.yml] *********
skipping: [hammerdb1]
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repo/tasks/setup_repo.yml for barman1, primary1, pemserver1, standby1, standby2

TASK [edb_devops.edb_postgres.setup_repo : Set the os variable] ****************
ok: [pemserver1]
ok: [barman1]
ok: [primary1]
ok: [standby1]
ok: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Check support for Operating System] ***
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Check support for Database engine] ***
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Check if Database Engine is supported] ***
skipping: [barman1]
skipping: [pemserver1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Validate Credentials] ***************
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Capture if bdr_nodes_ips if defined] ***
ok: [pemserver1]
ok: [barman1]
ok: [primary1]
ok: [standby1]
ok: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Validate tpa_subscription_token] ****
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Cleanup the repos based on force_repo] ***
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Install Postgres repositories] ******
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repo/tasks/PG_Debian_setuprepos.yml for pemserver1, barman1, primary1, standby1, standby2

TASK [edb_devops.edb_postgres.setup_repo : Verify if /etc/apt/auth.conf.d/edb.conf exists] ***
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Build EDB auth conf] ****************
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Install gpg] ************************
ok: [standby2]
ok: [pemserver1]
ok: [barman1]
ok: [primary1]
ok: [standby1]

TASK [edb_devops.edb_postgres.setup_repo : Install acl] ************************
ok: [pemserver1]
ok: [primary1]
ok: [barman1]
ok: [standby1]
ok: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Add EDB GPGP Debian keys] ***********
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Add EDB Debian repo] ****************
skipping: [pemserver1]
skipping: [barman1]
skipping: [primary1]
skipping: [standby1]
skipping: [standby2]

TASK [edb_devops.edb_postgres.setup_repo : Install apt-transport-https] ********
fatal: [standby2]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 533725 (python3)"}
fatal: [primary1]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 533725 (python3)"}
fatal: [barman1]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 533725 (python3)"}
fatal: [standby1]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 533725 (python3)"}
ok: [pemserver1]

TASK [edb_devops.edb_postgres.setup_repo : Add EDB Debian 9 repo] **************
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.setup_repo : Add PG Debian keys] *****************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.setup_repo : Add PG Debian repo] *****************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.setup_repo : Add additional Debian repositories] ***

TASK [edb_devops.edb_postgres.setup_repo : Install BDR packages if tpa_subscription_token is given] ***
skipping: [pemserver1] => (item=bdr4/release)
skipping: [pemserver1] => (item=harp/release)

TASK [edb_devops.edb_postgres.setup_repo : Install EDB repository 2.0] *********
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Include the install_dbserver.yml] ***
skipping: [hammerdb1]
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/install_dbserver/tasks/install_dbserver.yml for pemserver1

TASK [edb_devops.edb_postgres.install_dbserver : Set the os variable] **********
ok: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Check support for Operating System] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Check supported versions for Database engine] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Check if Database Engine is supported] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Remove Postgres packages] *****
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Install and Configure Postgres on RedHat] ***
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/install_dbserver/tasks/PG_Debian_install.yml for pemserver1

TASK [edb_devops.edb_postgres.install_dbserver : Install Postgres] *************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Install sslutils] *************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Install python-psycopg2] ******
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Install BDR packages for PG >= 14] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Stop the service postgresql@14-main] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Drop the default debian database] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.install_dbserver : Enable coredump based on enable_core_dump] ***
[WARNING]: noop task does not support when conditional
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Include the init_dbserver.yml] ***
skipping: [hammerdb1]
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/init_dbserver/tasks/init_dbserver.yml for pemserver1

TASK [edb_devops.edb_postgres.init_dbserver : Set the os variable] *************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Check support for Operating System] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Check supported versions for Database engine] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Reference pg_type variables] *****
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Reference ssl variables] *********
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Gather service facts] ************
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Open Postgres TCP port 5432] *****
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : include_tasks] *******************
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Update /etc/hosts file, based on variable etc_hosts_list] ***

TASK [edb_devops.edb_postgres.init_dbserver : Update /etc/hosts file, based on the inventory] ***
changed: [pemserver1] => (item={'inventory_hostname': 'pemserver1', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})
changed: [pemserver1] => (item={'inventory_hostname': 'barman1', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})
changed: [pemserver1] => (item={'inventory_hostname': 'primary1', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})
changed: [pemserver1] => (item={'inventory_hostname': 'standby1', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})
changed: [pemserver1] => (item={'inventory_hostname': 'standby2', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})
changed: [pemserver1] => (item={'inventory_hostname': 'hammerdb1', 'private_ip': 'xxx.xxx.xxx.xxx', 'ansible_host': 'xxx.xxx.xxx.xxx'})

TASK [edb_devops.edb_postgres.init_dbserver : Update system hostname] **********
changed: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres data directory exists] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres default data directory exists] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres log directory exists] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres wal directory exists] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres local wal archive directory exists] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Create unix socket domain directories] ***
ok: [pemserver1] => (item=/var/run/postgresql)

TASK [edb_devops.edb_postgres.init_dbserver : Create edb_audit_directory if defined] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Create hidden edb directory if not exists] ***
ok: [pemserver1 -> localhost]

TASK [edb_devops.edb_postgres.init_dbserver : Check if we have symlink for default data directory location] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure default data directory is deleted if pg_data is not default] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Ensure pg_data has symlink to default if pg_data is not default] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Copy global systemd unit file to /etc/systemd/system] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Update systemd unit file] ********
skipping: [pemserver1] => (item={'line': 'Description=Database server PG 14 - Instance: main', 'regexp': '^Description=.*'})
skipping: [pemserver1] => (item={'line': 'Environment=PGDATA=/var/lib/postgresql/14/main', 'regexp': '^Environment=PGDATA.*'})
skipping: [pemserver1] => (item={'line': 'PIDFile=/var/lib/postgresql/14/main/postmaster.pid', 'regexp': '^PIDFile=.*', 'insertafter': '^\\[Service\\]$'})
skipping: [pemserver1] => (item={'line': 'ExecStopPost=+/usr/bin/systemctl daemon-reload', 'regexp': '^ExecStopPost=.*', 'insertafter': '^\\[Service\\]$'})

TASK [edb_devops.edb_postgres.init_dbserver : Add LimitCORE in systemd file] ***
skipping: [pemserver1] => (item={'line': 'LimitCORE=infinity', 'regexp': '^LimitCORE=.*', 'insertafter': '^\\[Service\\]$'})

TASK [edb_devops.edb_postgres.init_dbserver : Check if we have PG_VERSION in pg_data] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Verify pg_wal and accordingly add in initdb] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Initialize database postgres service] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Initialize database postgres service] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Copy the postgresql.conf.template to the server] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Enable and start systemd service] ***
ok: [pemserver1]

TASK [Generate the pg_superuser_password] **************************************

TASK [edb_devops.edb_postgres.manage_dbserver : Create hidden pass directory if not exists] ***
ok: [pemserver1 -> localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Create passfile location] ******
ok: [pemserver1 -> localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Generate password or copy the password from pass file] ***
ok: [pemserver1 -> localhost]

TASK [edb_devops.edb_postgres.manage_dbserver : Make sure file has permission for owner only] ***
ok: [pemserver1 -> localhost]

TASK [edb_devops.edb_postgres.init_dbserver : Set pg_superuser_password] *******
ok: [pemserver1]

TASK [Set postgres superuser's database cluster password] **********************

TASK [edb_devops.edb_postgres.manage_dbserver : Check database is in read/write mode] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Manage optional users] *********
ok: [pemserver1] => (item={'name': 'postgres', 'pass': 'IrcDRBLIYpSlPIQFSAog'})

TASK [Set postgres primary_slot_name] ******************************************

TASK [edb_devops.edb_postgres.manage_dbserver : Check user defined parameters and update] ***
changed: [pemserver1] => (item={'name': 'primary_slot_name', 'value': 'pemserver1'})

TASK [edb_devops.edb_postgres.manage_dbserver : Register the restart requirements] ***
skipping: [pemserver1] => (item={'name': 'primary_slot_name', 'restart_required': False, 'prev_val_pretty': 'localhost', 'value_pretty': 'pemserver1', 'context': 'sighup', 'value': {'value': 'pemserver1', 'unit': None}, 'changed': True, 'invocation': {'module_args': {'login_unix_socket': '/var/run/postgresql', 'port': 5432, 'db': 'postgres', 'login_user': 'postgres', 'name': 'primary_slot_name', 'value': 'pemserver1', 'login_password': '', 'login_host': '', 'ssl_mode': 'prefer', 'reset': False, 'trust_input': True, 'ca_cert': None, 'session_role': None}}, 'failed': False, 'line_item': {'name': 'primary_slot_name', 'value': 'pemserver1'}, 'ansible_loop_var': 'line_item'})

TASK [edb_devops.edb_postgres.manage_dbserver : Reload the pg service] *********
changed: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Gather services facts] *********
ok: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Stop failover manager service if exists] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Restart the pg service] ********
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Start failover manager service if exists] ***
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Reset the restart_required] ****
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Send SSL key file] ***************
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Send SSL certificate file] *******
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Send SSL CA file] ****************
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : Send SSL CRL file] ***************
skipping: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have ca key exists or not] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have ca certificate exists or not] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have root.crt exists or not] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have root crl exists or not] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have server.key exists or not] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.init_dbserver : check if we have server.crt exists or not] ***
ok: [pemserver1]

TASK [create ssl extension in pg_database] *************************************

TASK [edb_devops.edb_postgres.manage_dbserver : Check database is in read/write mode] ***
ok: [pemserver1]

TASK [edb_devops.edb_postgres.manage_dbserver : Manage postgres extensions] ****
failed: [pemserver1] (item={'name': 'sslutils', 'database': 'postgres', 'state': 'present'}) => {"ansible_loop_var": "line_item", "changed": false, "line_item": {"database": "postgres", "name": "sslutils", "state": "present"}, "msg": "Extension sslutils is not available"}

TASK [edb_devops.edb_postgres.setup_replication : Include the setup_replication.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_efm : Include the setup_efm.yml] ***********
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_pgpool2 : Include the setup_pgpool2.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.manage_pgpool2 : Include the manage_pgpool2.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.manage_dbserver : Include the manage_dbserver.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_pemserver : Include the setup_pemserver.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_pgbouncer : Include the setup_pgbouncer.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.manage_pgbouncer : Include the manage_pgbouncer.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_barmanserver : Include the setup_barmanserver.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_barman : Include the setup_barman.yml] *****
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.setup_pemagent : Include the setup_pemagent.yml] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.autotuning : Include the autotuning.yml] *********
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.manage_dbpatches : Include manage patches tasks] ***
skipping: [hammerdb1]

TASK [edb_devops.edb_postgres.manage_efm : Include the manage_efm.yml] *********
skipping: [hammerdb1]

PLAY RECAP *********************************************************************
barman1                    : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
hammerdb1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0
pemserver1                 : ok=50   changed=4    unreachable=0    failed=1    skipped=47   rescued=0    ignored=0
primary1                   : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
standby1                   : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
standby2                   : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

```

**Comment by marangiop** [comment]
However, I am not sure how to check that my installation has gone correctly. If I check the status of the postgresql.service I see that it has not been restarted.

```
ubuntu@localhost:~/edb-ansible$ systemctl status postgresql
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
     Active: active (exited) since Wed 2022-10-12 15:30:23 UTC; 1 months 30 days ago
   Main PID: 47188 (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 2344)
     Memory: 0B
     CGroup: /system.slice/postgresql.service

Oct 12 15:30:23 db-node-2 systemd[1]: Starting PostgreSQL RDBMS...
Oct 12 15:30:23 db-node-2 systemd[1]: Finished PostgreSQL RDBMS.
```

**Comment by hannahms** [comment]
Hi @marangiop, 
It appears as though Ansible is running into computational thresholds while attempting to run the same task on all nodes at the same time. This can happen when deploying on localhost, so to prevent this from happening, a change needs to be made to the task failing. 
In the file `edb-ansible/roles/setup_repo/tasks/PG_Debian_setuprepos.yml` line 53 is a task named `Install apt-transport-https` 
```
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: true
    state: present
  become: true
```
To prevent this issue from occurring, only one node should be executed at a time, which can be set by adding a throttle value to the task.
``` 
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: true
    state: present
  become: true
  throttle: 1
  ```
This should fix the failure shown in the log file. This is under the assumption that all nodes are deployed on unique hosts.
 
  
I noticed that you are also deploying two standby's, a barman, pemserver and hammerdb node. While I can see that the `postgresql-14-sslutils` package was successfully installed on the pemserver node, 
```
TASK [edb_devops.edb_postgres.install_dbserver : Install sslutils] *************
ok: [pemserver1]
```
I cannot determine why this happened and if you would like to skip the install of this package on all nodes, the `pg_ssl=false` needs to be changed in two additional default variable definition places:
-`edb-ansible/roles/setup_replication/vars/PG_Debian.yml` - line 12
-`edb-ansible/roles/setup_pemserver/defaults/main.yml` - line 12
This should set the `pg_ssl=false` parameter for all nodes.

**Comment by marangiop** [comment]
Sorry for the confusion, it seems that I ran the command in the wrong folder of the repo. I am trying to deploy a primary only set up. This is why I am trying to run things on localhost

```
ubuntu@pemserver1:~/edb-ansible/playbook-examples/primary_only$ ansible-playbook playbook.yml --connection=local -i inventory.yml --extra-vars="pg_version=14 pg_type=PG enable_edb_repo=false"

PLAY [Postgres deployment playbook] ***********************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************
ok: [localhost]

TASK [Initialize the user defined variables] **************************************************************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Include the setup_repo.yml] ************************************************************************************
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repo/tasks/setup_repo.yml for localhost

TASK [edb_devops.edb_postgres.setup_repo : Set the os variable] *******************************************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Check support for Operating System] ****************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Check support for Database engine] *****************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Check if Database Engine is supported] *************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Validate Credentials] ******************************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Capture if bdr_nodes_ips if defined] ***************************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Validate tpa_subscription_token] *******************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Cleanup the repos based on force_repo] *************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Install Postgres repositories] *********************************************************************************
included: /home/ubuntu/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repo/tasks/PG_Debian_setuprepos.yml for localhost

TASK [edb_devops.edb_postgres.setup_repo : Verify if /etc/apt/auth.conf.d/edb.conf exists] ****************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Build EDB auth conf] *******************************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Install gpg] ***************************************************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Install acl] ***************************************************************************************************
ok: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Add EDB GPGP Debian keys] **************************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Add EDB Debian repo] *******************************************************************************************
skipping: [localhost]

TASK [edb_devops.edb_postgres.setup_repo : Install apt-transport-https] ***********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://downloads.enterprisedb.com/J8ogd3S3WRXmjZ03TMLY5gooxwUC41sx/enterprise/deb/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 18.66.97.7 443], E:The repository 'https://downloads.enterprisedb.com/J8ogd3S3WRXmjZ03TMLY5gooxwUC41sx/enterprise/deb/ubuntu focal InRelease' is no longer signed."}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

```

I am getting a new error. Any thoughts?

**Comment by vibhorkumar123** [comment]
Based on the last messages, the issue is unrelated to the subject of this issue. @marangiop, Can you please confirm if we can close this issue? You can open another GitHub issue if you are still facing challenges with Debian.

**Comment by Sagebati** [comment]
Hi, 

I have the same problem, I modified `init_db` and `install_db` to set the pg_ssl to false 
```
$ grep "pg_ssl: false"  -R .ansible/collections/ansible_collections/edb_devops/edb_postgres/
.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/install_dbserver/defaults/main.yml:pg_ssl: false
.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/init_dbserver/defaults/main.yml:pg_ssl: false
```
But I still get this error: It searches for a package that doesn't need to be installed. 
```
fatal: [util2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'postgresql-14-sslutils'. 'dict object' has no attribute 'postgresql-14-sslutils'\n\nThe error appears to be in '/home/sam/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/install_dbserver/tasks/validate_install_dbserver.yml': line 168, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Check that all required packages have been installed\n  ^ here\n"}
```

**Comment by hannahms** [comment]
Hi there,
I see the issue, and I don't think the proposed fix will completely solve the errors, as it will still add a package to the list and does not fix for other distributions + `pg_type`'s. I can fix for all OS/`pg_type`'s and re-release.
